In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Diabetes_preprocessing_2.csv')
df.head()

gender  age  admission_type_id  discharge_disposition_id  \
0       0   15                  0                         0   
1       0   25                  0                         0   
2       1   35                  0                         0   
3       1   45                  0                         0   
4       1   55                  0                         0   

   admission_source_id  time_in_hospital  num_lab_procedures  num_procedures  \
0                    0                 3                  59               0   
1                    0                 2                  11               5   
2                    0                 2                  44               1   
3                    0                 1                  51               0   
4                    1                 3                  31               6   

   num_medications  diag_1  ...  glyburide  insulin  change  diabetesMed  \
0               18       8  ...          0        1       1            1   
1               13       8  ...          0        0       0            1   
2               16       8  ...          0        1       1            1   
3                8       7  ...          0        0       1            1   
4               16       1  ...          0        0       0            1   

   readmitted  service_utilization  Asian  Caucasian  Hispanic  Other  
0           0                    0      0          1         0      0  
1           0                    3      0          0         0      0  
2           0                    0      0          1         0      0  
3           0                    0      0          1         0      0  
4           0                    0      0          1         0      0  

[5 rows x 27 columns]

In [3]:
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PowerTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier, GradientBoostingClassifier,StackingClassifier,BaggingClassifier
from sklearn.model_selection import train_test_split,GridSearchCV,KFold,cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.pipeline import Pipeline
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn.naive_bayes import GaussianNB
import lightgbm as ltb
from sklearn.metrics import roc_curve
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [4]:
X=df.drop('readmitted',axis=1)
y=df.readmitted
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30,random_state=1)
print('X_train', X_train.shape)
print('y_train', y_train.shape)
print('X_test', X_test.shape)
print('y_test', y_test.shape)

X_train (68463, 26)
y_train (68463,)
X_test (29342, 26)
y_test (29342,)


In [10]:
scores = pd.DataFrame(columns=['Model_Name','Train_Accuracy', 'Test_Accuracy',
                               'Train_f1','Train_precision','Train_recall','Train_auc_roc',
                              'Test_f1','Test_precision','Test_recall','Test_auc_roc'])
scores

Empty DataFrame
Columns: [Model_Name, Train_Accuracy, Test_Accuracy, Train_f1, Train_precision, Train_recall, Train_auc_roc, Test_f1, Test_precision, Test_recall, Test_auc_roc]
Index: []

### Logistic Regression

In [11]:
pipe = Pipeline((
("pt", PowerTransformer()),
("lr", LogisticRegression()),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
lr1 = pd.Series({'Model_Name': "Logistic Regression Base",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,
                 'Test_f1':f,'Test_recall':r,'Test_precision':p,'Test_auc_roc':au,
                 'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,'Train_auc_roc':tau})
scores= scores.append(lr1, ignore_index=True)
scores

Training Accuracy
0.8858069322115595
Testing Accuracy
0.8845341149205916
Cross validation score 0.8858069333454859
[[25954     0]
 [ 3388     0]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     25954
           1       0.00      0.00      0.00      3388

    accuracy                           0.88     29342
   macro avg       0.44      0.50      0.47     29342
weighted avg       0.78      0.88      0.83     29342

precision 0.0
recall 0.0
f1_score 0.0
roc_auc_score 0.5
[[60645     0]
 [ 7818     0]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     60645
           1       0.00      0.00      0.00      7818

    accuracy                           0.89     68463
   macro avg       0.44      0.50      0.47     68463
weighted avg       0.78      0.89      0.83     68463

precision 0.0
recall 0.0
f1_score 0.0
roc_auc_score 0.5


Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0  Logistic Regression Base        0.885807       0.884534       0.0   

   Train_precision  Train_recall  Train_auc_roc  Test_f1  Test_precision  \
0              0.0           0.0            0.5      0.0             0.0   

   Test_recall  Test_auc_roc  
0          0.0           0.5

### Logistic Regression Balanced

In [12]:
pipe = Pipeline((
("pt", PowerTransformer()),
("lr", LogisticRegression(class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Logistic Regression Balanced",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.5924513971050056
Testing Accuracy
0.5996182945947788
Cross validation score 0.5923199220740081
[[15518 10436]
 [ 1312  2076]]
              precision    recall  f1-score   support

           0       0.92      0.60      0.73     25954
           1       0.17      0.61      0.26      3388

    accuracy                           0.60     29342
   macro avg       0.54      0.61      0.49     29342
weighted avg       0.83      0.60      0.67     29342

precision 0.16592071611253198
recall 0.6127508854781583
f1_score 0.2611320754716981
roc_auc_score 0.6053274347249002
[[35782 24863]
 [ 3039  4779]]
              precision    recall  f1-score   support

           0       0.92      0.59      0.72     60645
           1       0.16      0.61      0.26      7818

    accuracy                           0.59     68463
   macro avg       0.54      0.60      0.49     68463
weighted avg       0.83      0.59      0.67     68463

precision 0.16122393900546522
recall 0.6112816577129

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327

### Decision Tree

In [13]:
pipe = Pipeline((
("pt", PowerTransformer()),
("dt", DecisionTreeClassifier(random_state=10)),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Decision Tree",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.9999853935702496
Testing Accuracy
0.7860064071978734
Cross validation score 0.7847596428155927
[[22437  3517]
 [ 2762   626]]
              precision    recall  f1-score   support

           0       0.89      0.86      0.88     25954
           1       0.15      0.18      0.17      3388

    accuracy                           0.79     29342
   macro avg       0.52      0.52      0.52     29342
weighted avg       0.81      0.79      0.80     29342

precision 0.1510982379917934
recall 0.1847697756788666
f1_score 0.16624618244589034
roc_auc_score 0.5246303991286373
[[60645     0]
 [    1  7817]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60645
           1       1.00      1.00      1.00      7818

    accuracy                           1.00     68463
   macro avg       1.00      1.00      1.00     68463
weighted avg       1.00      1.00      1.00     68463

precision 1.0
recall 0.9998720900486058
f1_score 0.9

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630

### Decision Tree Balanced

In [14]:
pipe = Pipeline((
("pt", PowerTransformer()),
("dt", DecisionTreeClassifier(random_state=10,class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Decision Tree Balanced",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.9999853935702496
Testing Accuracy
0.8047167882216618
Cross validation score 0.8035142681299041
[[23143  2811]
 [ 2919   469]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89     25954
           1       0.14      0.14      0.14      3388

    accuracy                           0.80     29342
   macro avg       0.52      0.52      0.52     29342
weighted avg       0.80      0.80      0.80     29342

precision 0.14298780487804877
recall 0.1384297520661157
f1_score 0.14067186562687461
roc_auc_score 0.5150613736827457
[[60644     1]
 [    0  7818]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60645
           1       1.00      1.00      1.00      7818

    accuracy                           1.00     68463
   macro avg       1.00      1.00      1.00     68463
weighted avg       1.00      1.00      1.00     68463

precision 0.999872106407469
recall 1.0
f1_score 0.9

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061

### Decision Tree Tuned

In [15]:
pipe = Pipeline((
("pt", PowerTransformer()),
("dt", DecisionTreeClassifier(random_state=10,class_weight='balanced',criterion = 'entropy',max_depth = 5)),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Decision Tree Tuned",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.6184800549201759
Testing Accuracy
0.6203735260036807
Cross validation score 0.6061227357841678
[[16211  9743]
 [ 1396  1992]]
              precision    recall  f1-score   support

           0       0.92      0.62      0.74     25954
           1       0.17      0.59      0.26      3388

    accuracy                           0.62     29342
   macro avg       0.55      0.61      0.50     29342
weighted avg       0.83      0.62      0.69     29342

precision 0.16974861525351512
recall 0.5879574970484062
f1_score 0.2634397936917278
roc_auc_score 0.6062812837788845
[[37648 22997]
 [ 3123  4695]]
              precision    recall  f1-score   support

           0       0.92      0.62      0.74     60645
           1       0.17      0.60      0.26      7818

    accuracy                           0.62     68463
   macro avg       0.55      0.61      0.50     68463
weighted avg       0.84      0.62      0.69     68463

precision 0.16954355048389427
recall 0.6005372217958

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281

### Random Forest

In [16]:
pipe = Pipeline((
("pt", PowerTransformer()),
("rf", RandomForestClassifier(random_state=10)),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Random Forest",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.9999707871404993
Testing Accuracy
0.8849090041578624
Cross validation score 0.8857631121360203
[[25948     6]
 [ 3371    17]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     25954
           1       0.74      0.01      0.01      3388

    accuracy                           0.88     29342
   macro avg       0.81      0.50      0.47     29342
weighted avg       0.87      0.88      0.83     29342

precision 0.7391304347826086
recall 0.005017709563164109
f1_score 0.009967751392553502
roc_auc_score 0.5023932656623711
[[60645     0]
 [    2  7816]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60645
           1       1.00      1.00      1.00      7818

    accuracy                           1.00     68463
   macro avg       1.00      1.00      1.00     68463
weighted avg       1.00      1.00      1.00     68463

precision 1.0
recall 0.9997441800972116
f1_score 

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   
5                 Random Forest        0.885763       0.884909  0.999872   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   
5         1.000000      0.999744       0.999872  0.009968        0.739130   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281  
5     0.005018      0.502393

### Random Forest Balanced

In [17]:
pipe = Pipeline((
("pt", PowerTransformer()),
("rf", RandomForestClassifier(random_state=10,class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Random Forest Balanced",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.9999561807107489
Testing Accuracy
0.8844659532410879
Cross validation score 0.8857046870569969
[[25947     7]
 [ 3383     5]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     25954
           1       0.42      0.00      0.00      3388

    accuracy                           0.88     29342
   macro avg       0.65      0.50      0.47     29342
weighted avg       0.83      0.88      0.83     29342

precision 0.4166666666666667
recall 0.0014757969303423849
f1_score 0.0029411764705882353
roc_auc_score 0.5006030444927584
[[60644     1]
 [    2  7816]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     60645
           1       1.00      1.00      1.00      7818

    accuracy                           1.00     68463
   macro avg       1.00      1.00      1.00     68463
weighted avg       1.00      1.00      1.00     68463

precision 0.9998720736855571
recall 0.999744180

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   
5                 Random Forest        0.885763       0.884909  0.999872   
6        Random Forest Balanced        0.885705       0.884466  0.999808   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   
5         1.000000      0.999744       0.999872  0.009968        0.739130   
6         0.999872      0.999744       0.999864  0.002941        0.416667   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281  
5     0.005018      0.502393  
6     0.001476      0.500603

### Random Forest Tuned

In [19]:
pipe = Pipeline((
("pt", PowerTransformer()),
("rf", RandomForestClassifier(random_state=10,n_estimators = 5, max_depth = 3,class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "Random Forest Tuned",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.668156522501205
Testing Accuracy
0.6719719173880444
Cross validation score 0.6367238568706428
[[18047  7907]
 [ 1718  1670]]
              precision    recall  f1-score   support

           0       0.91      0.70      0.79     25954
           1       0.17      0.49      0.26      3388

    accuracy                           0.67     29342
   macro avg       0.54      0.59      0.52     29342
weighted avg       0.83      0.67      0.73     29342

precision 0.17437610942883994
recall 0.49291617473435656
f1_score 0.2576166602391053
roc_auc_score 0.5941308931003986
[[41869 18776]
 [ 3943  3875]]
              precision    recall  f1-score   support

           0       0.91      0.69      0.79     60645
           1       0.17      0.50      0.25      7818

    accuracy                           0.67     68463
   macro avg       0.54      0.59      0.52     68463
weighted avg       0.83      0.67      0.73     68463

precision 0.17107412476270364
recall 0.4956510616525

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   
5                 Random Forest        0.885763       0.884909  0.999872   
6        Random Forest Balanced        0.885705       0.884466  0.999808   
7           Random Forest Tuned        0.636724       0.671972  0.254357   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   
5         1.000000      0.999744       0.999872  0.009968        0.739130   
6         0.999872      0.999744       0.999864  0.002941        0.416667   
7         0.171074      0.495651       0.593023  0.257617        0.174376   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281  
5     0.005018      0.502393  
6     0.001476      0.500603  
7     0.492916      0.594131

### XG Boost

In [20]:
pipe = Pipeline((
("pt", PowerTransformer()),
("gb", XGBClassifier()),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "XG Boost",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

[14:10:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy
0.8937528299957641
Testing Accuracy
0.8836820939267943
[14:10:58] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:11:03] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavio

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   
5                 Random Forest        0.885763       0.884909  0.999872   
6        Random Forest Balanced        0.885705       0.884466  0.999808   
7           Random Forest Tuned        0.636724       0.671972  0.254357   
8                      XG Boost        0.884551       0.883682  0.134460   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   
5         1.000000      0.999744       0.999872  0.009968        0.739130   
6         0.999872      0.999744       0.999864  0.002941        0.416667   
7         0.171074      0.495651       0.593023  0.257617        0.174376   
8         0.964164      0.072269       0.535961  0.025136        0.389381   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281  
5     0.005018      0.502393  
6     0.001476      0.500603  
7     0.492916      0.594131  
8     0.012987      0.505164

### XG Boost Balanced

In [21]:
pipe = Pipeline((
("pt", PowerTransformer()),
("gb", XGBClassifier(scale_pos_weight=7.73)),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "XG Boost Balanced",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

[14:13:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy
0.7391583775177833
Testing Accuracy
0.678072387703633
[14:13:12] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:13:17] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0      Logistic Regression Base        0.885807       0.884534  0.000000   
1  Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                 Decision Tree        0.784760       0.786006  0.999936   
3        Decision Tree Balanced        0.803514       0.804717  0.999936   
4           Decision Tree Tuned        0.606123       0.620374  0.264433   
5                 Random Forest        0.885763       0.884909  0.999872   
6        Random Forest Balanced        0.885705       0.884466  0.999808   
7           Random Forest Tuned        0.636724       0.671972  0.254357   
8                      XG Boost        0.884551       0.883682  0.134460   
9             XG Boost Balanced        0.683712       0.678072  0.405011   

   Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0         0.000000      0.000000       0.500000  0.000000        0.000000   
1         0.161224      0.611282       0.600653  0.261132        0.165921   
2         1.000000      0.999872       0.999936  0.166246        0.151098   
3         0.999872      1.000000       0.999992  0.140672        0.142988   
4         0.169544      0.600537       0.610665  0.263440        0.169749   
5         1.000000      0.999744       0.999872  0.009968        0.739130   
6         0.999872      0.999744       0.999864  0.002941        0.416667   
7         0.171074      0.495651       0.593023  0.257617        0.174376   
8         0.964164      0.072269       0.535961  0.025136        0.389381   
9         0.273833      0.777437       0.755830  0.257857        0.175696   

   Test_recall  Test_auc_roc  
0     0.000000      0.500000  
1     0.612751      0.605327  
2     0.184770      0.524630  
3     0.138430      0.515061  
4     0.587957      0.606281  
5     0.005018      0.502393  
6     0.001476      0.500603  
7     0.492916      0.594131  
8     0.012987      0.505164  
9     0.484357      0.593858

### XG Boost Tuned

In [22]:
pipe = Pipeline((
("pt", PowerTransformer()),
("gb", XGBClassifier(learning_rate=.1,max_depth = 4, gamma = 0,scale_pos_weight=7.72)),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "XG Boost Tuned",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

[14:14:36] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Training Accuracy
0.6319910024392738
Testing Accuracy
0.6281098766273601
[14:14:41] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
[14:14:45] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavio

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0       Logistic Regression Base        0.885807       0.884534  0.000000   
1   Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                  Decision Tree        0.784760       0.786006  0.999936   
3         Decision Tree Balanced        0.803514       0.804717  0.999936   
4            Decision Tree Tuned        0.606123       0.620374  0.264433   
5                  Random Forest        0.885763       0.884909  0.999872   
6         Random Forest Balanced        0.885705       0.884466  0.999808   
7            Random Forest Tuned        0.636724       0.671972  0.254357   
8                       XG Boost        0.884551       0.883682  0.134460   
9              XG Boost Balanced        0.683712       0.678072  0.405011   
10                XG Boost Tuned        0.624220       0.628110  0.282664   

    Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0          0.000000      0.000000       0.500000  0.000000        0.000000   
1          0.161224      0.611282       0.600653  0.261132        0.165921   
2          1.000000      0.999872       0.999936  0.166246        0.151098   
3          0.999872      1.000000       0.999992  0.140672        0.142988   
4          0.169544      0.600537       0.610665  0.263440        0.169749   
5          1.000000      0.999744       0.999872  0.009968        0.739130   
6          0.999872      0.999744       0.999864  0.002941        0.416667   
7          0.171074      0.495651       0.593023  0.257617        0.174376   
8          0.964164      0.072269       0.535961  0.025136        0.389381   
9          0.273833      0.777437       0.755830  0.257857        0.175696   
10         0.181798      0.634945       0.633278  0.268044        0.173437   

    Test_recall  Test_auc_roc  
0      0.000000      0.500000  
1      0.612751      0.605327  
2      0.184770      0.524630  
3      0.138430      0.515061  
4      0.587957      0.606281  
5      0.005018      0.502393  
6      0.001476      0.500603  
7      0.492916      0.594131  
8      0.012987      0.505164  
9      0.484357      0.593858  
10     0.589728      0.611424

### LightGBM 

In [23]:
pipe = Pipeline((
("pt", PowerTransformer()),
("lg", LGBMClassifier()),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "LightGBM",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.8868585951535866
Testing Accuracy
0.8846704382795992
Cross validation score 0.8858653594912639
[[25945     9]
 [ 3375    13]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.94     25954
           1       0.59      0.00      0.01      3388

    accuracy                           0.88     29342
   macro avg       0.74      0.50      0.47     29342
weighted avg       0.85      0.88      0.83     29342

precision 0.5909090909090909
recall 0.0038370720188902006
f1_score 0.007624633431085044
roc_auc_score 0.5017451523306288
[[60640     5]
 [ 7741    77]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94     60645
           1       0.94      0.01      0.02      7818

    accuracy                           0.89     68463
   macro avg       0.91      0.50      0.48     68463
weighted avg       0.89      0.89      0.83     68463

precision 0.9390243902439024
recall 0.0098490662

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0       Logistic Regression Base        0.885807       0.884534  0.000000   
1   Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                  Decision Tree        0.784760       0.786006  0.999936   
3         Decision Tree Balanced        0.803514       0.804717  0.999936   
4            Decision Tree Tuned        0.606123       0.620374  0.264433   
5                  Random Forest        0.885763       0.884909  0.999872   
6         Random Forest Balanced        0.885705       0.884466  0.999808   
7            Random Forest Tuned        0.636724       0.671972  0.254357   
8                       XG Boost        0.884551       0.883682  0.134460   
9              XG Boost Balanced        0.683712       0.678072  0.405011   
10                XG Boost Tuned        0.624220       0.628110  0.282664   
11                      LightGBM        0.885865       0.884670  0.019494   

    Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0          0.000000      0.000000       0.500000  0.000000        0.000000   
1          0.161224      0.611282       0.600653  0.261132        0.165921   
2          1.000000      0.999872       0.999936  0.166246        0.151098   
3          0.999872      1.000000       0.999992  0.140672        0.142988   
4          0.169544      0.600537       0.610665  0.263440        0.169749   
5          1.000000      0.999744       0.999872  0.009968        0.739130   
6          0.999872      0.999744       0.999864  0.002941        0.416667   
7          0.171074      0.495651       0.593023  0.257617        0.174376   
8          0.964164      0.072269       0.535961  0.025136        0.389381   
9          0.273833      0.777437       0.755830  0.257857        0.175696   
10         0.181798      0.634945       0.633278  0.268044        0.173437   
11         0.939024      0.009849       0.504883  0.007625        0.590909   

    Test_recall  Test_auc_roc  
0      0.000000      0.500000  
1      0.612751      0.605327  
2      0.184770      0.524630  
3      0.138430      0.515061  
4      0.587957      0.606281  
5      0.005018      0.502393  
6      0.001476      0.500603  
7      0.492916      0.594131  
8      0.012987      0.505164  
9      0.484357      0.593858  
10     0.589728      0.611424  
11     0.003837      0.501745

### LightGBM Balanced

In [24]:
pipe = Pipeline((
("pt", PowerTransformer()),
("lg", LGBMClassifier(class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "LightGBM Balanced",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.6628397820720682
Testing Accuracy
0.6409583532138232
Cross validation score 0.6364312695708121
[[16852  9102]
 [ 1433  1955]]
              precision    recall  f1-score   support

           0       0.92      0.65      0.76     25954
           1       0.18      0.58      0.27      3388

    accuracy                           0.64     29342
   macro avg       0.55      0.61      0.52     29342
weighted avg       0.84      0.64      0.71     29342

precision 0.17681106991046397
recall 0.5770365997638724
f1_score 0.2706818968501212
roc_auc_score 0.6131696060389833
[[39922 20723]
 [ 2360  5458]]
              precision    recall  f1-score   support

           0       0.94      0.66      0.78     60645
           1       0.21      0.70      0.32      7818

    accuracy                           0.66     68463
   macro avg       0.58      0.68      0.55     68463
weighted avg       0.86      0.66      0.72     68463

precision 0.20847179252129408
recall 0.6981325147096

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0       Logistic Regression Base        0.885807       0.884534  0.000000   
1   Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                  Decision Tree        0.784760       0.786006  0.999936   
3         Decision Tree Balanced        0.803514       0.804717  0.999936   
4            Decision Tree Tuned        0.606123       0.620374  0.264433   
5                  Random Forest        0.885763       0.884909  0.999872   
6         Random Forest Balanced        0.885705       0.884466  0.999808   
7            Random Forest Tuned        0.636724       0.671972  0.254357   
8                       XG Boost        0.884551       0.883682  0.134460   
9              XG Boost Balanced        0.683712       0.678072  0.405011   
10                XG Boost Tuned        0.624220       0.628110  0.282664   
11                      LightGBM        0.885865       0.884670  0.019494   
12             LightGBM Balanced        0.636431       0.640958  0.321068   

    Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0          0.000000      0.000000       0.500000  0.000000        0.000000   
1          0.161224      0.611282       0.600653  0.261132        0.165921   
2          1.000000      0.999872       0.999936  0.166246        0.151098   
3          0.999872      1.000000       0.999992  0.140672        0.142988   
4          0.169544      0.600537       0.610665  0.263440        0.169749   
5          1.000000      0.999744       0.999872  0.009968        0.739130   
6          0.999872      0.999744       0.999864  0.002941        0.416667   
7          0.171074      0.495651       0.593023  0.257617        0.174376   
8          0.964164      0.072269       0.535961  0.025136        0.389381   
9          0.273833      0.777437       0.755830  0.257857        0.175696   
10         0.181798      0.634945       0.633278  0.268044        0.173437   
11         0.939024      0.009849       0.504883  0.007625        0.590909   
12         0.208472      0.698133       0.678211  0.270682        0.176811   

    Test_recall  Test_auc_roc  
0      0.000000      0.500000  
1      0.612751      0.605327  
2      0.184770      0.524630  
3      0.138430      0.515061  
4      0.587957      0.606281  
5      0.005018      0.502393  
6      0.001476      0.500603  
7      0.492916      0.594131  
8      0.012987      0.505164  
9      0.484357      0.593858  
10     0.589728      0.611424  
11     0.003837      0.501745  
12     0.577037      0.613170

### LightGBM Tuned

In [25]:
pipe = Pipeline((
("pt", PowerTransformer()),
("lg", LGBMClassifier(objective='binary',max_bin=7,num_leaves=7,max_depth=4, random_state=5,class_weight='balanced')),
))
pipe.fit(X_train,y_train)
print("Training Accuracy")
print(pipe.score(X_train,y_train))
print("Testing Accuracy")
print(pipe.score(X_test,y_test))
te_acc=pipe.score(X_test,y_test)
score=cross_val_score(estimator=pipe,X=X_train,y=y_train,scoring='accuracy',cv=5)
print('Cross validation score',np.mean(score))
tr_acc=np.mean(score)
pred=pipe.predict(X_test)
predx=pipe.predict(X_train)
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))
print('precision',precision_score(y_test,pred))
p=precision_score(y_test,pred)
print('recall',recall_score(y_test,pred))
r=recall_score(y_test,pred)
print('f1_score',f1_score(y_test,pred))
f=f1_score(y_test,pred)
print('roc_auc_score',roc_auc_score(y_test,pred))
au=roc_auc_score(y_test,pred)
print(confusion_matrix(y_train,predx))
print(classification_report(y_train,predx))
print('precision',precision_score(y_train,predx))
tp=precision_score(y_train,predx)
print('recall',recall_score(y_train,predx))
tr=recall_score(y_train,predx)
print('f1_score',f1_score(y_train,predx))
tf=f1_score(y_train,predx)
print('roc_auc_score',roc_auc_score(y_train,predx))
tau=roc_auc_score(y_train,predx)
add = pd.Series({'Model_Name': "LightGBM Tuned",'Train_Accuracy':tr_acc,'Test_Accuracy': te_acc,'Test_f1':f,'Test_recall':r,
                 'Test_precision':p,'Test_auc_roc':au,'Train_f1': tf,'Train_recall':tr,'Train_precision':tp,
                 'Train_auc_roc':tau})
scores= scores.append(add, ignore_index=True)
scores

Training Accuracy
0.6147700217635803
Testing Accuracy
0.6179537863812964
Cross validation score 0.6122868851128197
[[16080  9874]
 [ 1336  2052]]
              precision    recall  f1-score   support

           0       0.92      0.62      0.74     25954
           1       0.17      0.61      0.27      3388

    accuracy                           0.62     29342
   macro avg       0.55      0.61      0.50     29342
weighted avg       0.84      0.62      0.69     29342

precision 0.1720610430991112
recall 0.6056670602125147
f1_score 0.2679900744416873
roc_auc_score 0.6126123695915004
[[37200 23445]
 [ 2929  4889]]
              precision    recall  f1-score   support

           0       0.93      0.61      0.74     60645
           1       0.17      0.63      0.27      7818

    accuracy                           0.61     68463
   macro avg       0.55      0.62      0.50     68463
weighted avg       0.84      0.61      0.68     68463

precision 0.17254888120279524
recall 0.62535175236633

Model_Name  Train_Accuracy  Test_Accuracy  Train_f1  \
0       Logistic Regression Base        0.885807       0.884534  0.000000   
1   Logistic Regression Balanced        0.592320       0.599618  0.255152   
2                  Decision Tree        0.784760       0.786006  0.999936   
3         Decision Tree Balanced        0.803514       0.804717  0.999936   
4            Decision Tree Tuned        0.606123       0.620374  0.264433   
5                  Random Forest        0.885763       0.884909  0.999872   
6         Random Forest Balanced        0.885705       0.884466  0.999808   
7            Random Forest Tuned        0.636724       0.671972  0.254357   
8                       XG Boost        0.884551       0.883682  0.134460   
9              XG Boost Balanced        0.683712       0.678072  0.405011   
10                XG Boost Tuned        0.624220       0.628110  0.282664   
11                      LightGBM        0.885865       0.884670  0.019494   
12             LightGBM Balanced        0.636431       0.640958  0.321068   
13                LightGBM Tuned        0.612287       0.617954  0.270469   

    Train_precision  Train_recall  Train_auc_roc   Test_f1  Test_precision  \
0          0.000000      0.000000       0.500000  0.000000        0.000000   
1          0.161224      0.611282       0.600653  0.261132        0.165921   
2          1.000000      0.999872       0.999936  0.166246        0.151098   
3          0.999872      1.000000       0.999992  0.140672        0.142988   
4          0.169544      0.600537       0.610665  0.263440        0.169749   
5          1.000000      0.999744       0.999872  0.009968        0.739130   
6          0.999872      0.999744       0.999864  0.002941        0.416667   
7          0.171074      0.495651       0.593023  0.257617        0.174376   
8          0.964164      0.072269       0.535961  0.025136        0.389381   
9          0.273833      0.777437       0.755830  0.257857        0.175696   
10         0.181798      0.634945       0.633278  0.268044        0.173437   
11         0.939024      0.009849       0.504883  0.007625        0.590909   
12         0.208472      0.698133       0.678211  0.270682        0.176811   
13         0.172549      0.625352       0.619379  0.267990        0.172061   

    Test_recall  Test_auc_roc  
0      0.000000      0.500000  
1      0.612751      0.605327  
2      0.184770      0.524630  
3      0.138430      0.515061  
4      0.587957      0.606281  
5      0.005018      0.502393  
6      0.001476      0.500603  
7      0.492916      0.594131  
8      0.012987      0.505164  
9      0.484357      0.593858  
10     0.589728      0.611424  
11     0.003837      0.501745  
12     0.577037      0.613170  
13     0.605667      0.612612